// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2IL1cpNqZE-SYNrGmYbcX2GxwZXfrOTc',
    appId: '1:825391844432:web:500cd2e50b2bb13c7cd555',
    messagingSenderId: '825391844432',
    projectId: 'dinotis-4375d',
    authDomain: 'dinotis-4375d.firebaseapp.com',
    storageBucket: 'dinotis-4375d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9vPRBGyZpTT9HFQyPi6KtIJff9Z_tbO8',
    appId: '1:825391844432:android:911bb445a95f7abf7cd555',
    messagingSenderId: '825391844432',
    projectId: 'dinotis-4375d',
    storageBucket: 'dinotis-4375d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXH31XM-rZ9aRMWKJb-okkkwXecNiIgg',
    appId: '1:825391844432:ios:48057f905870285f7cd555',
    messagingSenderId: '825391844432',
    projectId: 'dinotis-4375d',
    storageBucket: 'dinotis-4375d.appspot.com',
    iosClientId: '825391844432-rgaibqd887bueb5epi2b3lclteps9e2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinotis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfXH31XM-rZ9aRMWKJb-okkkwXecNiIgg',
    appId: '1:825391844432:ios:48057f905870285f7cd555',
    messagingSenderId: '825391844432',
    projectId: 'dinotis-4375d',
    storageBucket: 'dinotis-4375d.appspot.com',
    iosClientId: '825391844432-rgaibqd887bueb5epi2b3lclteps9e2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinotis',
  );
}
